### PR TITLE
Making the site mobile adaptable

### PR DESCRIPTION
**Pull request by ceb3745**
Added the module react-device-detect.

Had a little issue with unit testing this because I didn't know how to only mock a portion of the module. I wanted to mock the isMobile but not the MobileView or the BrowserView. I ended up adding an optional prop which if set and if the env was test it would set what I wanted for unit testing so that I could test both mobile and browser.

I also modified the css a bit so it was more mobile friendly.

I made it so that on mobile you could hide and show the data table and it that everything is in one straight line down the screen for mobile.

It works reasonably well.

Let me know if you see anything immediately wrong. I know there is probably some ways that I am doing styling that I should change.

Not everyone I want to do is done yet. There are still some issues when viewing stuff on mobile.

### CODE REVIEW

**Comment by michaelmior** [comment]
Looks like a good start! One of the main things I see is that the "For questions..." text shows up on top of everything else and gets in the way. I'll attach a screenshot.

**Comment by michaelmior** [comment]
￼

**Comment by michaelmior** [comment]
Screenshot_20200114-150813

**Comment by ceb3745** [comment]
Yeah! Thats one of the things on my list to fix!

**Pull request closed without merging**
